
import json
import os

import requests
from dotenv import load_dotenv

from app.context.context_store import ContextStore


load_dotenv()


class ContextAgent:

    GEMINI_URL = (
        "https://generativelanguage.googleapis.com/"
        "v1beta/models/gemini-flash-latest:generateContent"
    )

    def __init__(self):

        self.api_key = os.getenv(
            "GEMINI_API_KEY"
        )

        self.context_store = ContextStore()

    def _fallback_answer(self, context: dict, question: str) -> str:
        identity = context.get("identity", {})
        ordering = context.get("ordering_profile", {})
        customer_segment = context.get("customer_segment", "customer")
        summary = context.get("summary", "")
        favorite_cuisines = ordering.get("favorite_cuisines", [])
        total_orders = ordering.get("total_orders", 0)
        total_spend = ordering.get("total_spend", 0)
        name = identity.get("name", "This customer")

        cuisine_list = ", ".join(
            item.get("name", "")
            for item in favorite_cuisines[:3]
            if item.get("name")
        ) or "diverse cuisines"

        if summary:
            return summary

        answer = (
            f"{name} is a {customer_segment} customer with {total_orders} orders "
            f"and a total spend of ₹{total_spend:,.0f}. "
            f"Their top cuisines include {cuisine_list}. "
            f"This answer is based on the local synthesized context because "
            f"GEMINI_API_KEY is not configured."
        )

        if "tell me about" in question.lower() or "describe" in question.lower():
            return answer

        return (
            f"Based on the available customer context, {name} appears to be a "
            f"{customer_segment} customer with {total_orders} orders. "
            f"Their most common cuisines are {cuisine_list}."
        )

    # ========================================================
    # PUBLIC API
    # ========================================================

    def ask(self, user_id: str, question: str):

        context = self.context_store.get(
            user_id
        )

        if not context:
            return {
                "error": (
                    f"No synthesized context found "
                    f"for user '{user_id}'."
                )
            }

        if not self.api_key:
            answer = self._fallback_answer(
                context,
                question,
            )
            return {
                "user_id": user_id,
                "question": question,
                "answer": answer,
                "context": context,
            }

        prompt = self._build_prompt(
            context,
            question
        )

        answer = self._call_gemini(
            prompt
        )

        return {
            "user_id": user_id,
            "question": question,
            "answer": answer,
            "context": context,
        }

    # ========================================================
    # PROMPT
    # ========================================================

    def _build_prompt(
        self,
        context: dict,
        question: str
    ):

        context_json = json.dumps(
            context,
            indent=2,
            ensure_ascii=False
        )

        return f"""
You are the Context Intelligence Agent for FoodLens,
a food-delivery platform.

Your job is to answer questions about a customer using
ONLY the synthesized customer context supplied below.

The context has already been generated by the platform's
Context Layer from raw platform activity such as:

- orders
- restaurants
- cuisines
- ratings
- order timing
- spending
- recency
- frequency
- loyalty
- behavioral trends

Do NOT invent facts.

Do NOT assume information that is not present.

If the answer cannot be determined from the context,
clearly say that the available customer context does
not contain enough information.

You should synthesize multiple context fields when
answering open-ended questions.

For example, if asked:

"Tell me about this customer"

combine relevant information about:

- customer segment
- ordering frequency
- spending
- favorite cuisines
- restaurant loyalty
- recent activity
- ordering time
- trends
- behavioral insights

Do not simply dump the JSON back to the user.

Instead, provide a concise, natural-language explanation.

When useful, include specific numbers from the context.

Customer Context:
-----------------

{context_json}

User Question:
--------------

{question}

Answer the question using the customer context above.
"""

    # ========================================================
    # GEMINI API
    # ========================================================

    def _call_gemini(
        self,
        prompt: str
    ):

        if not self.api_key:
            raise RuntimeError(
                "GEMINI_API_KEY is not configured; "
                "using the fallback deterministic context answer instead."
            )

        headers = {
            "Content-Type": "application/json",
            "x-goog-api-key": self.api_key,
        }

        payload = {
            "contents": [
                {
                    "role": "user",
                    "parts": [
                        {
                            "text": prompt
                        }
                    ]
                }
            ],
            "generationConfig": {
                "temperature": 0.2,
                "maxOutputTokens": 700,
            }
        }

        try:

            response = requests.post(
                self.GEMINI_URL,
                headers=headers,
                json=payload,
                timeout=30,
            )

            response.raise_for_status()

            data = response.json()

            return self._extract_text(
                data
            )

        except requests.HTTPError as exc:

            try:
                error_data = response.json()

            except Exception:
                error_data = response.text

            raise RuntimeError(
                f"Gemini API error: "
                f"{error_data}"
            ) from exc

        except requests.RequestException as exc:

            raise RuntimeError(
                f"Unable to connect to Gemini API: "
                f"{exc}"
            ) from exc

    # ========================================================
    # RESPONSE PARSER
    # ========================================================

    @staticmethod
    def _extract_text(data):

        candidates = data.get(
            "candidates",
            []
        )

        if not candidates:
            raise RuntimeError(
                "Gemini returned no candidates."
            )

        content = candidates[0].get(
            "content",
            {}
        )

        parts = content.get(
            "parts",
            []
        )

        text_parts = []

        for part in parts:

            text = part.get("text")

            if text:
                text_parts.append(text)

        if not text_parts:

            raise RuntimeError(
                "Gemini returned an empty response."
            )

        return "\n".join(
            text_parts
        ).strip()


